on:
#  schedule:
#    - cron:  '30 5 * * *'
  workflow_dispatch:
    ~

jobs:
  combine:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout Kamalisk/arkhamdb-json-data
        uses: actions/checkout@v4
        with:
          repository: Kamalisk/arkhamdb-json-data
          path: json
      - run: python main/combine.py
      - name: Push combined.json
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main
        
